version: "3.7"

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=4200
    command: ng serve
