version: "3"
services:
  mongo-node:
    image: mongo
    restart: always
    volumes:
      - .db :/data/db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
