version: '3.4'

services:
  dockerexpress:
    image: dockerexpress
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      -  /app/node_modules  
    environment:
      - PORT=3000 